# -*- coding: utf-8 -*-
"""FITCoursework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fpveVL59gGPDPeTr93K99PhtLlw3wAvm
"""
import os
import subprocess
import scapy

subprocess.run(["sudo", "ip", "4", "route", "add", "default", "via", "inet6"])

import scapy
from scapy.all import rdpcap

pcap_file_path = 'Data/link1_1-VPN/link1_Test11_34_54.pcap'
packets = rdpcap(pcap_file_path)

for i in range(min(5, len(packets))):
    print("Packet {}:\n{}\n".format(i + 1, packets[i].summary()))

print("Total number of packets: {}".format(len(packets)))


def is_vpn(packet):
    return (
        scapy.layers.inet.IP in packet and
        (
            (scapy.layers.inet.TCP in packet and (packet[scapy.layers.inet.TCP].dport == 1194 or packet[scapy.layers.inet.TCP].sport == 1194)) or
            (scapy.layers.inet.UDP in packet and (packet[scapy.layers.inet.UDP].dport == 500 or packet[scapy.layers.inet.UDP].sport == 500))
        )
    )

pcap_file_path = '/content/drive/MyDrive/FIT/Data/link1_1-VPN/link1_Test11_37_33.pcap'
packets = rdpcap(pcap_file_path)

vpn_packets = [packet for packet in packets if is_vpn(packet)]
non_vpn_packets = [packet for packet in packets if not is_vpn(packet)]

print("Total packets: {}".format(len(packets)))
print("VPN packets: {}".format(len(vpn_packets)))
print("Non-VPN packets: {}".format(len(non_vpn_packets)))


def detect_vpn_packets(pcap_file):
    common_vpn_ports = [1194, 1723, 500, 4500, 443, 1701]
    vpn_packet_count = 0
    total_packet_count = 0

    try:
        packets = rdpcap(pcap_file)

        for packet in packets:
            total_packet_count += 1

            if packet.haslayer(scapy.layers.inet.TCP):
                tcp_layer = packet[scapy.layers.inet.TCP]
                if tcp_layer.sport in common_vpn_ports or tcp_layer.dport in common_vpn_ports:
                    vpn_packet_count += 1
            elif packet.haslayer(scapy.layers.inet.UDP):
                udp_layer = packet[scapy.layers.inet.UDP]
                if udp_layer.sport in common_vpn_ports or udp_layer.dport in common_vpn_ports:
                    vpn_packet_count += 1

    except FileNotFoundError:
        print("File not found: {}".format(pcap_file))
        return
    except Exception as e:
        print("An error occurred while processing {}: {}".format(pcap_file, e))
        return

    print("Total packets in {}: {}, Suspected VPN packets: {}".format(pcap_file, total_packet_count, vpn_packet_count))


root_folder_path = '/content/drive/MyDrive/FIT/Data/'

for folder_name, sub_folders, file_names in os.walk(root_folder_path):
    for filename in file_names:
        if filename.endswith(".pcap"):
            file_path = os.path.join(folder_name, filename)
            detect_vpn_packets(file_path)
